# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  batch: true

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      npm run publish:sprint
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/__sapper__/export/"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId).zip"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId).zip'
      artifactName: 'sheaft-site-sprint'
  - script: |
      npm run publish:staging
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/__sapper__/export/"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId).zip"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId).zip'
      artifactName: 'sheaft-site-staging'
  - script: |
      npm run publish:production
  - task: ArchiveFiles@2
    displayName: "Archive files"
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)/__sapper__/export/"
      includeRootFolder: false
      archiveFile: "$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId).zip"
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/publish_output/build$(Build.BuildId).zip'
      artifactName: 'sheaft-site-production'
